/**
 * Doc index — every entry maps a /docs/<slug> URL to a customer
 * doc in docs/customer/. The list is generated by walking
 * docs/customer/ at build time; the canonical list lives there.
 *
 * This file is the marketing-site mirror of that list. The
 * check-internal-links.mjs script asserts every href here
 * resolves to a file in docs/customer/.
 */

export interface DocEntry {
  slug: string;
  title: string;
  summary: string;
  category: "Getting started" | "Mailboxes" | "Admin" | "Security" | "API" | "Billing" | "Reference";
}

export const DOCS: DocEntry[] = [
  { slug: "getting-started", title: "Getting started", summary: "Create an account, add your first domain, and send your first message.", category: "Getting started" },
  { slug: "domains", title: "Adding a domain", summary: "Verify ownership and set up MX, SPF, DKIM, and DMARC for your domain.", category: "Getting started" },
  { slug: "domain-verification", title: "Domain verification", summary: "How Orvix proves you control a domain before serving mail for it.", category: "Getting started" },
  { slug: "dns-troubleshooting", title: "DNS troubleshooting", summary: "Diagnose and fix common DNS issues that block mail delivery.", category: "Getting started" },

  { slug: "mailboxes", title: "Mailboxes", summary: "Create, configure, and remove mailboxes for your team.", category: "Mailboxes" },
  { slug: "aliases", title: "Aliases", summary: "Forward mail from one address to another without a separate mailbox.", category: "Mailboxes" },
  { slug: "groups", title: "Distribution groups", summary: "Send mail to a list and have it delivered to every member.", category: "Mailboxes" },
  { slug: "rules", title: "Inbox rules", summary: "Automatically move, label, or forward incoming messages.", category: "Mailboxes" },
  { slug: "signatures", title: "Signatures", summary: "Set a default signature for every message you send.", category: "Mailboxes" },
  { slug: "vacation", title: "Vacation reply", summary: "Send automatic out-of-office replies for a date range.", category: "Mailboxes" },
  { slug: "forwarding", title: "Mail forwarding", summary: "Forward mail from one mailbox to an external address.", category: "Mailboxes" },
  { slug: "webmail", title: "Using webmail", summary: "A tour of the Orvix webmail interface — folders, search, compose.", category: "Mailboxes" },

  { slug: "organization", title: "Organization", summary: "Settings that apply to your whole organization.", category: "Admin" },
  { slug: "invitations", title: "Invitations", summary: "Invite teammates and set their role when they accept.", category: "Admin" },
  { slug: "roles", title: "Roles and permissions", summary: "What each role can do, and how to change a member's role.", category: "Admin" },
  { slug: "ownership-transfer", title: "Ownership transfer", summary: "Hand ownership of an organization to another member.", category: "Admin" },

  { slug: "password-reset", title: "Password reset", summary: "Reset the password on a mailbox or your own account.", category: "Security" },
  { slug: "mfa", title: "Multi-factor authentication", summary: "Add a second factor to your account with TOTP.", category: "Security" },
  { slug: "security", title: "Security overview", summary: "How Orvix secures your mail in transit and at rest.", category: "Security" },
  { slug: "mx", title: "MX records", summary: "Point your domain's MX records at Orvix.", category: "Security" },
  { slug: "spf", title: "SPF", summary: "Authorize Orvix to send mail for your domain.", category: "Security" },
  { slug: "dkim", title: "DKIM", summary: "Cryptographically sign every message Orvix sends for you.", category: "Security" },
  { slug: "dmarc", title: "DMARC", summary: "Tell receivers what to do with mail that fails SPF or DKIM.", category: "Security" },

  { slug: "api", title: "API overview", summary: "Authenticate, paginate, and rate-limit with the Orvix REST API.", category: "API" },
  { slug: "api-keys", title: "API keys", summary: "Create and revoke API keys for your organization.", category: "API" },

  { slug: "billing-provider", title: "Billing provider", summary: "How Orvix integrates with the configured billing provider.", category: "Billing" },
  { slug: "plans", title: "Plans", summary: "What each plan includes and the limits on each one.", category: "Billing" },
  { slug: "quotas", title: "Quotas", summary: "Per-mailbox storage quotas and per-organization send limits.", category: "Billing" },
  { slug: "subscription-states", title: "Subscription states", summary: "Trialing, active, past due, grace period, suspended, cancelled.", category: "Billing" },
  { slug: "usage", title: "Usage", summary: "Track your storage and sends against your plan.", category: "Billing" },

  { slug: "status", title: "Status and incidents", summary: "How we communicate outages and incidents.", category: "Reference" },
  { slug: "support", title: "Support", summary: "How to get help — what's covered on each plan.", category: "Reference" },
  { slug: "troubleshooting", title: "Troubleshooting", summary: "Common problems and how to fix them.", category: "Reference" },
  { slug: "privacy", title: "Privacy", summary: "How Orvix handles the personal data in your account.", category: "Reference" },
  { slug: "index", title: "Doc index", summary: "Every doc, organized by category.", category: "Reference" },
];

export function getDocBySlug(slug: string): DocEntry | undefined {
  return DOCS.find((d) => d.slug === slug);
}
