package mailcontrol

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	admindomain "github.com/orvix/orvix/internal/admin/domain"
	adminmailbox "github.com/orvix/orvix/internal/admin/mailbox"
	"github.com/orvix/orvix/internal/audit"
	"github.com/orvix/orvix/internal/platform/kernel"
)

// Service orchestrates the existing production admin services for the
// Platform Super Admin mail-control surface. It never fabricates a
// tenant: every operation requires an explicit tenantID, and every
// resource is re-verified tenant-owned through the underlying service
// (which already scopes by tenant_id in its SQL).
type Service struct {
	domains   *admindomain.Service
	mailboxes *adminmailbox.Service
	repo      *Repository
	audit     *audit.ExtendedStore
	outbox    *kernel.OutboxRepository
	clock     func() time.Time
}

type Ports struct {
	Domains   *admindomain.Service
	Mailboxes *adminmailbox.Service
	Audit     *audit.ExtendedStore
	Outbox    *kernel.OutboxRepository
}

func NewService(repo *Repository, ports Ports) *Service {
	return &Service{
		domains:   ports.Domains,
		mailboxes: ports.Mailboxes,
		repo:      repo,
		audit:     ports.Audit,
		outbox:    ports.Outbox,
		clock:     func() time.Time { return time.Now().UTC() },
	}
}

func (s *Service) now() time.Time { return s.clock() }

func (s *Service) requireTenant(tenantID uint) error {
	if tenantID == 0 {
		return ErrTenantRequired
	}
	return nil
}

// verifyTenantEligible rejects tenant 0, nonexistent tenants, deleted
// tenants, and suspended/inactive tenants. It is the lifecycle gate
// every platform provisioning mutation passes through before touching
// tenant resources. A lifecycle lookup failure fails CLOSED with a
// typed unavailable error rather than proceeding on unknown state.
func (s *Service) verifyTenantEligible(ctx context.Context, tenantID uint) error {
	if err := s.requireTenant(tenantID); err != nil {
		return err
	}
	st, err := s.repo.TenantEligible(ctx, tenantID)
	if err != nil {
		return kernel.Wrap(kernel.ErrCodeUnavailable, "tenant lifecycle check unavailable", err)
	}
	if !st.Exists {
		return ErrTenantNotFound
	}
	if st.Deleted {
		return ErrTenantDeleted
	}
	if !st.Active {
		return ErrTenantSuspended
	}
	return nil
}

func (s *Service) auditRecord(ctx context.Context, actorID uint, action, target string, tenantID uint, result, reason string) {
	if s.audit == nil {
		return
	}
	_ = s.audit.Record(ctx, &audit.ExtendedEntry{
		ActorID: actorID, TenantID: tenantID, Action: action, Target: target,
		Result: result, Reason: reason, Timestamp: s.now(),
	})
}

// ── Domains ────────────────────────────────────────────────────────

// CreateDomain is the Platform Super Admin domain provisioning entry
// point. It reuses the canonical admin domain provisioning service
// (internal/admin/domain.ProvisionDomain) for the entire transactional
// body — name normalization/IDNA, tenant-scoped ownership, plan/limit
// enforcement under FOR UPDATE, the domain insert WITHOUT any
// tenant_id=0 fallback, lifecycle state, DKIM generation through the
// shared transaction helper, and the canonical audit records. The
// platform layer adds: explicit tenant lifecycle verification,
// the operator audit record, and the transactional outbox event
// carrying only publishable DNS requirements.
//
// DNS requirements are generated by the caller through the existing
// dnsops service (the handler owns cfg/public-IP inputs) and passed in
// as publishable records; this service persists them in the outbox
// event payload and returns them in the response. Nothing here ever
// asserts DNS is verified — verification is a separate operator action.
func (s *Service) CreateDomain(ctx context.Context, req PlatformCreateDomainRequest, tenantID, actorID uint, dnsRequirements []PlatformDNSRequirement) (*PlatformCreateDomainResult, error) {
	if err := s.verifyTenantEligible(ctx, tenantID); err != nil {
		return nil, err
	}

	adminReq := admindomain.CreateDomainRequest{
		Name:        strings.TrimSpace(req.Name),
		Description: req.Description,
		Status:      req.Status,
	}
	if req.Limits != nil {
		adminReq.Limits = &admindomain.DomainLimits{
			MaxMailboxes:          req.Limits.MaxMailboxes,
			MaxAliases:            req.Limits.MaxAliases,
			DefaultMailboxQuotaMB: req.Limits.DefaultMailboxQuotaMB,
			MaxMailboxQuotaMB:     req.Limits.MaxMailboxQuotaMB,
		}
	}
	if req.DKIM != nil && req.DKIM.Generate {
		adminReq.DKIM = &admindomain.DKIMOptions{Generate: true, Selector: req.DKIM.Selector}
	}

	// The canonical provisioning transaction: plan-cap enforcement is
	// atomic under concurrency (tenant plan row locked FOR UPDATE on
	// PostgreSQL), duplicate names return the deterministic typed
	// conflict, DKIM is generated through the shared transaction helper,
	// and a failure at ANY step — including audit/outbox writes inside
	// the admin service — rolls the whole transaction back.
	result, err := s.domains.ProvisionDomain(ctx, adminReq, tenantID)
	if err != nil {
		switch {
		case errors.Is(err, admindomain.ErrDomainAlreadyExists):
			return nil, kernel.Conflict("domain already exists")
		case errors.Is(err, admindomain.ErrDomainLimitReached):
			return nil, kernel.QuotaExceeded("domain limit reached for the organization plan")
		case errors.Is(err, admindomain.ErrPlanUnavailable):
			return nil, kernel.NewError(kernel.ErrCodeUnavailable, "organization plan is unavailable")
		case errors.Is(err, admindomain.ErrInvalidDomainName):
			return nil, kernel.ValidationError(map[string]string{"name": "invalid domain name"})
		case errors.Is(err, admindomain.ErrInvalidDomainStatus):
			return nil, kernel.ValidationError(map[string]string{"status": "unsupported domain status"})
		case errors.Is(err, admindomain.ErrInvalidLimit):
			return nil, kernel.ValidationError(map[string]string{"limits": "invalid limit value"})
		case errors.Is(err, admindomain.ErrLimitExceedsPlan):
			return nil, kernel.QuotaExceeded("limit exceeds the organization plan")
		case errors.Is(err, admindomain.ErrLimitContradiction):
			return nil, kernel.ValidationError(map[string]string{"limits": "contradictory limit values"})
		case errors.Is(err, admindomain.ErrDescriptionTooLong):
			return nil, kernel.ValidationError(map[string]string{"description": "description too long"})
		case errors.Is(err, admindomain.ErrInvalidDKIMSelector):
			return nil, kernel.ValidationError(map[string]string{"dkim": "invalid dkim selector"})
		case errors.Is(err, admindomain.ErrDomainForbidden):
			return nil, kernel.Forbidden("domain provisioning is not permitted for this tenant")
		}
		return nil, kernel.Wrap(kernel.ErrCodeInternal, "platform domain provisioning failed", err)
	}

	out := &PlatformCreateDomainResult{
		Domain:           s.mapPlatformDomain(ctx, *result.Domain, tenantID),
		EffectiveLimits:  mapEffectiveLimits(result.EffectiveLimits),
		DNSRequirements:  dnsRequirements,
		DNSNextStep:      "publish_and_verify_dns",
		PublicDNSChanged: false,
		Idempotent:       result.Idempotent,
	}
	if result.DKIM != nil {
		out.DKIM = &PlatformDKIMResult{
			Selector:      result.DKIM.Selector,
			PublicDNSTxt:  result.DKIM.PublicDNSTxt,
			DNSRecordName: result.DKIM.DNSRecordName,
		}
	}
	if result.Plan != nil {
		out.Plan = &PlatformPlanSummary{
			Plan:                  result.Plan.Plan,
			MaxDomains:            result.Plan.MaxDomains,
			MaxDomainsUnlimited:   result.Plan.MaxDomainsUnlimited,
			DomainsUsed:           result.Plan.DomainsUsed,
			RemainingDomains:      result.Plan.RemainingDomains,
			MaxMailboxes:          result.Plan.MaxMailboxes,
			MaxMailboxesUnlimited: result.Plan.MaxMailboxesUnlimited,
			MailboxesUsed:         result.Plan.MailboxesUsed,
			RemainingMailboxes:    result.Plan.RemainingMailboxes,
		}
	}

	// Operator audit record. The payload is publishable data only —
	// domain, status, whether DKIM was requested (never key material),
	// and the DNS requirement count.
	s.auditRecord(ctx, actorID, "platform.domain.create", fmt.Sprintf("domain:%d", result.Domain.ID), tenantID, "success", fmt.Sprintf("name:%s status:%s dkim:%t", result.Domain.Name, result.Domain.Status, req.DKIM != nil && req.DKIM.Generate))

	// Transactional outbox evidence: only publishable records travel in
	// the payload. Best-effort (a failed enqueue must not fail a
	// committed provisioning), matching every other platform service.
	if s.outbox != nil {
		_ = s.outbox.Enqueue(ctx, s.repo.db, "platform.domain.provisioned", fmt.Sprintf("domain:%d", result.Domain.ID), map[string]any{
			"domain_id":        result.Domain.ID,
			"name":             result.Domain.Name,
			"status":           result.Domain.Status,
			"tenant_id":        tenantID,
			"dkim_generated":   req.DKIM != nil && req.DKIM.Generate,
			"dns_requirements": dnsRequirements,
		}, s.now())
	}

	return out, nil
}

// mapPlatformDomain projects an admin domain into the platform
// contract, including the configured (domain-level) mail-access mode.
func (s *Service) mapPlatformDomain(ctx context.Context, d admindomain.AdminDomain, tenantID uint) PlatformDomain {
	mode, _ := s.domains.GetMailAccessMode(ctx, d.ID, tenantID)
	return PlatformDomain{
		ID: d.ID, TenantID: tenantID, Name: d.Name, Status: d.Status, Plan: d.Plan,
		Description: d.Description, MailboxCount: d.MailboxCount, AliasCount: d.AliasCount,
		DKIMEnabled: d.DKIMEnabled, DKIMSelector: d.DKIMSelector, DMARCEnabled: d.DMARCEnabled,
		MailAccessMode: string(mode), CreatedAt: d.CreatedAt, UpdatedAt: d.UpdatedAt,
	}
}

func mapEffectiveLimits(in admindomain.EffectiveLimits) PlatformEffectiveLimits {
	return PlatformEffectiveLimits{
		MaxMailboxes:                   in.MaxMailboxes,
		MaxMailboxesUnlimited:          in.MaxMailboxesUnlimited,
		MaxMailboxesInherited:          in.MaxMailboxesInherited,
		MaxAliases:                     in.MaxAliases,
		MaxAliasesUnlimited:            in.MaxAliasesUnlimited,
		MaxAliasesInherited:            in.MaxAliasesInherited,
		DefaultMailboxQuotaMB:          in.DefaultMailboxQuotaMB,
		MaxMailboxQuotaMB:              in.MaxMailboxQuotaMB,
		MaxMailboxQuotaUnlimited:       in.MaxMailboxQuotaUnlimited,
		MaxMailboxQuotaInherited:       in.MaxMailboxQuotaInherited,
		DefaultMailboxQuotaMBInherited: in.DefaultMailboxQuotaMBInherited,
	}
}

func (s *Service) ListDomains(ctx context.Context, f PlatformDomainFilter) (*PlatformDomainList, error) {
	if f.TenantID == 0 {
		return nil, ErrTenantRequired
	}
	statusPtr := stringPtrIf(f.Status != "", f.Status)
	tenantPtr := uintPtrIf(f.TenantID != 0, f.TenantID)
	domains, total, err := s.domains.ListDomains(ctx, admindomain.DomainFilter{
		TenantID: tenantPtr, Status: statusPtr, Search: f.Search, Limit: sanitizeLimit(f.Limit), Offset: f.Offset,
	})
	if err != nil {
		return nil, kernel.Wrap(kernel.ErrCodeInternal, "list platform domains", err)
	}
	out := make([]PlatformDomain, 0, len(domains))
	for _, d := range domains {
		mode, _ := s.domains.GetMailAccessMode(ctx, d.ID, f.TenantID)
		out = append(out, PlatformDomain{
			ID: d.ID, TenantID: f.TenantID, Name: d.Name, Status: d.Status, Plan: d.Plan,
			Description: d.Description, MailboxCount: d.MailboxCount, AliasCount: d.AliasCount,
			DKIMEnabled: d.DKIMEnabled, DKIMSelector: d.DKIMSelector, DMARCEnabled: d.DMARCEnabled,
			MailAccessMode: string(mode), CreatedAt: d.CreatedAt, UpdatedAt: d.UpdatedAt,
		})
	}
	return &PlatformDomainList{Domains: out, Total: total, Limit: sanitizeLimit(f.Limit), Offset: f.Offset}, nil
}

func (s *Service) GetDomain(ctx context.Context, id, tenantID uint) (*PlatformDomain, error) {
	if err := s.requireTenant(tenantID); err != nil {
		return nil, err
	}
	d, err := s.domains.GetDomain(ctx, id, tenantID)
	if err != nil {
		if errors.Is(err, admindomain.ErrDomainNotFound) {
			return nil, kernel.NotFound("domain")
		}
		return nil, kernel.Wrap(kernel.ErrCodeInternal, "get platform domain", err)
	}
	if d == nil {
		return nil, kernel.NotFound("domain")
	}
	mode, _ := s.domains.GetMailAccessMode(ctx, d.ID, tenantID)
	aliases, _ := s.domains.CountAliasesByDomain(ctx, d.ID, tenantID)
	return &PlatformDomain{
		ID: d.ID, TenantID: tenantID, Name: d.Name, Status: d.Status, Plan: d.Plan,
		Description: d.Description, MailboxCount: d.MailboxCount, AliasCount: int(aliases),
		DKIMEnabled: d.DKIMEnabled, DKIMSelector: d.DKIMSelector, DMARCEnabled: d.DMARCEnabled,
		MailAccessMode: string(mode), CreatedAt: d.CreatedAt, UpdatedAt: d.UpdatedAt,
	}, nil
}

// SetDomainStatus applies an allowed lifecycle transition for an
// explicit tenant-owned domain through the production admin service.
// Ownership is verified first: a cross-tenant id yields NOT_FOUND, and
// the guarded tenant-scoped UPDATE would otherwise silently affect zero
// rows.
func (s *Service) SetDomainStatus(ctx context.Context, id, tenantID uint, status, reason string, actorID uint) error {
	if err := s.requireTenant(tenantID); err != nil {
		return err
	}
	if _, err := s.domains.GetDomain(ctx, id, tenantID); err != nil {
		if errors.Is(err, admindomain.ErrDomainNotFound) {
			return kernel.NotFound("domain")
		}
		return kernel.Wrap(kernel.ErrCodeInternal, "verify platform domain ownership", err)
	}
	if err := s.domains.SetDomainStatus(ctx, id, tenantID, status, reason); err != nil {
		return kernel.Wrap(kernel.ErrCodeInternal, "set platform domain status", err)
	}
	s.auditRecord(ctx, actorID, "platform.domain.status", fmt.Sprintf("domain:%d status:%s", id, status), tenantID, "success", reason)
	return nil
}

// SetMailAccessMode sets the canonical domain mail-access mode used by
// the SMTP policy path. It validates the mode and re-checks ownership
// through the production service, which enforces tenant_id in SQL.
func (s *Service) SetMailAccessMode(ctx context.Context, id, tenantID uint, mode string, actorID uint) error {
	if err := s.requireTenant(tenantID); err != nil {
		return err
	}
	if _, ok := admindomain.ParseMailAccessMode(mode); !ok {
		return kernel.ValidationError(map[string]string{"mail_access_mode": "must be internal_only or internal_external"})
	}
	if err := s.domains.SetMailAccessMode(ctx, id, tenantID, mode); err != nil {
		return kernel.Wrap(kernel.ErrCodeInternal, "set mail access mode", err)
	}
	s.auditRecord(ctx, actorID, "platform.domain.mail_access_mode", fmt.Sprintf("domain:%d mode:%s", id, mode), tenantID, "success", "")
	return nil
}

// ── Mailboxes ──────────────────────────────────────────────────────

// CreateMailbox is the Platform Super Admin mailbox provisioning entry
// point. It reuses the canonical admin mailbox service's transactional
// creation (domain ownership + lifecycle eligibility, atomic domain
// cap enforcement, quota bounds, Argon2id hashing through the shared
// hasher, transactional audit, and in-transaction system-folder
// provisioning). The platform layer adds: explicit tenant lifecycle
// verification, the REQUIRED explicit mail-access mode, the operator
// audit record, and the transactional outbox event. The password is
// used once to derive the hash and is never returned or logged.
func (s *Service) CreateMailbox(ctx context.Context, req PlatformCreateMailboxRequest, tenantID, actorID uint) (*PlatformCreateMailboxResult, error) {
	if err := s.verifyTenantEligible(ctx, tenantID); err != nil {
		return nil, err
	}
	// The platform route requires an explicit mode and accepts only
	// the two concrete values. "inherit" is rejected here by design:
	// platform provisioning must make an explicit per-mailbox decision.
	mode, ok := adminmailbox.ParseMailAccessMode(req.MailAccessMode)
	if !ok || mode == adminmailbox.MailAccessInherit {
		return nil, kernel.ValidationError(map[string]string{"mail_access_mode": "must be internal_only or internal_external"})
	}
	modeStr := string(mode)

	adminReq := adminmailbox.CreateMailboxRequest{
		Email:               req.Email,
		Name:                req.Name,
		Password:            req.Password,
		QuotaMB:             req.QuotaMB,
		SendLimit:           req.SendLimitPerHour,
		ForcePasswordChange: req.ForcePasswordChange,
		MailAccessMode:      &modeStr,
	}

	created, err := s.mailboxes.CreateMailboxWithFolders(ctx, adminReq, tenantID)
	if err != nil {
		return nil, s.mapMailboxCreateError(err)
	}

	s.auditRecord(ctx, actorID, "platform.mailbox.create", fmt.Sprintf("mailbox:%d", created.Mailbox.ID), tenantID, "success", fmt.Sprintf("email:%s mode:%s", created.Mailbox.Email, modeStr))
	if s.outbox != nil {
		_ = s.outbox.Enqueue(ctx, s.repo.db, "platform.mailbox.provisioned", fmt.Sprintf("mailbox:%d", created.Mailbox.ID), map[string]any{
			"mailbox_id":       created.Mailbox.ID,
			"email":            created.Mailbox.Email,
			"tenant_id":        tenantID,
			"mail_access_mode": modeStr,
		}, s.now())
	}

	return &PlatformCreateMailboxResult{
		Mailbox: PlatformMailbox{
			ID: created.Mailbox.ID, TenantID: tenantID, DomainID: created.Mailbox.DomainID,
			Email: created.Mailbox.Email, Name: created.Mailbox.Name,
			Status: string(created.Mailbox.Status), IsAdmin: created.Mailbox.IsAdmin,
			QuotaMB: created.Mailbox.QuotaMB, UsedBytes: created.Mailbox.UsedBytes,
			MailAccessMode:          created.Mailbox.MailAccessMode,
			EffectiveMailAccessMode: created.Mailbox.EffectiveMailAccessMode,
			CreatedAt:               created.Mailbox.CreatedAt, UpdatedAt: created.Mailbox.UpdatedAt,
		},
	}, nil
}

// mapMailboxCreateError maps canonical admin mailbox/domain errors to
// the typed platform contract. Cross-tenant domain lookups resolve to
// not-found without disclosing the other tenant.
func (s *Service) mapMailboxCreateError(err error) error {
	switch {
	case errors.Is(err, adminmailbox.ErrInvalidEmail):
		return kernel.ValidationError(map[string]string{"email": "invalid email address"})
	case errors.Is(err, adminmailbox.ErrPasswordRequired):
		return kernel.ValidationError(map[string]string{"password": "password is required"})
	case errors.Is(err, adminmailbox.ErrMailboxExists):
		return kernel.Conflict("mailbox already exists")
	case errors.Is(err, adminmailbox.ErrInvalidQuota):
		return kernel.ValidationError(map[string]string{"quota_mb": "invalid quota value"})
	case errors.Is(err, admindomain.ErrDomainNotFound):
		return kernel.NotFound("domain")
	case errors.Is(err, admindomain.ErrDomainDisabled):
		return kernel.Conflict("domain is disabled")
	case errors.Is(err, admindomain.ErrDomainSuspended):
		return kernel.Conflict("domain is suspended")
	case errors.Is(err, admindomain.ErrDomainLocked):
		return kernel.Conflict("domain is locked")
	case errors.Is(err, admindomain.ErrDomainUnavailable):
		return kernel.Conflict("domain is unavailable")
	case errors.Is(err, admindomain.ErrMailboxLimitReached):
		return kernel.QuotaExceeded("domain mailbox limit reached")
	case errors.Is(err, admindomain.ErrQuotaExceedsDomain):
		return kernel.QuotaExceeded("requested quota exceeds the domain maximum")
	}
	return kernel.Wrap(kernel.ErrCodeInternal, "platform mailbox provisioning failed", err)
}

// SetMailboxAccessMode is the guarded per-mailbox access-mode mutation.
// Tenant ownership is enforced in the SQL mutation predicate; the
// version guard provides optimistic concurrency; the canonical audit
// record and the transactional outbox event provide evidence. A
// cross-tenant id resolves to NOT_FOUND (zero rows affected, no
// disclosure); a stale version resolves to a precondition failure.
func (s *Service) SetMailboxAccessMode(ctx context.Context, id, tenantID uint, req PlatformSetMailboxAccessModeRequest, actorID uint) (*PlatformMailboxAccessModeResult, error) {
	if err := s.requireTenant(tenantID); err != nil {
		return nil, err
	}
	cfg, eff, newVersion, err := s.mailboxes.SetMailAccessMode(ctx, id, tenantID, req.MailAccessMode, req.ExpectedVersion)
	if err != nil {
		switch {
		case errors.Is(err, adminmailbox.ErrMailboxNotFound):
			return nil, kernel.NotFound("mailbox")
		case errors.Is(err, adminmailbox.ErrMailboxVersionConflict):
			return nil, kernel.NewError(kernel.ErrCodePreconditionFail, "mailbox version conflict: re-read the mailbox and retry")
		case errors.Is(err, adminmailbox.ErrInvalidMailAccessMode):
			return nil, kernel.ValidationError(map[string]string{"mail_access_mode": "must be inherit, internal_only, or internal_external"})
		}
		return nil, kernel.Wrap(kernel.ErrCodeInternal, "set mailbox access mode", err)
	}
	s.auditRecord(ctx, actorID, "platform.mailbox.access_mode", fmt.Sprintf("mailbox:%d mode:%s version:%d", id, cfg, newVersion), tenantID, "success", "")
	if s.outbox != nil {
		_ = s.outbox.Enqueue(ctx, s.repo.db, "mailbox.access_mode.changed", fmt.Sprintf("mailbox:%d", id), map[string]any{
			"mailbox_id":       id,
			"tenant_id":        tenantID,
			"mail_access_mode": cfg,
		}, s.now())
	}
	return &PlatformMailboxAccessModeResult{
		ID: id, MailAccessMode: cfg, EffectiveMailAccessMode: eff, Version: newVersion,
	}, nil
}

func (s *Service) ListMailboxes(ctx context.Context, f PlatformMailboxFilter) (*PlatformMailboxList, error) {
	if err := s.requireTenant(f.TenantID); err != nil {
		return nil, err
	}
	statusPtr := (*adminmailbox.AdminMailboxStatus)(nil)
	if f.Status != "" {
		v := adminmailbox.AdminMailboxStatus(f.Status)
		statusPtr = &v
	}
	tenantPtr := f.TenantID
	var domainPtr *uint
	if f.DomainID > 0 {
		domainPtr = &f.DomainID
	}
	boxes, total, err := s.mailboxes.ListMailboxes(ctx, adminmailbox.MailboxFilter{
		DomainID: domainPtr, TenantID: &tenantPtr, Status: statusPtr, Search: f.Search, Limit: sanitizeLimit(f.Limit), Offset: f.Offset,
	})
	if err != nil {
		return nil, kernel.Wrap(kernel.ErrCodeInternal, "list platform mailboxes", err)
	}
	out := make([]PlatformMailbox, 0, len(boxes))
	for _, m := range boxes {
		out = append(out, s.projectMailbox(m, f.TenantID))
	}
	return &PlatformMailboxList{Mailboxes: out, Total: total, Limit: sanitizeLimit(f.Limit), Offset: f.Offset}, nil
}

// projectMailbox maps an admin mailbox into the platform contract,
// attaching the configured and effective mail-access modes.
func (s *Service) projectMailbox(m adminmailbox.AdminMailbox, tenantID uint) PlatformMailbox {
	effective := m.EffectiveMailAccessMode
	if effective == "" {
		effective = string(adminmailbox.MailAccessInherit)
	}
	// Best-effort effective-mode resolution for reads that predate the
	// field (the service attaches it on Get; List keeps it cheap).
	if m.EffectiveMailAccessMode == "" {
		if _, eff, _, err := s.mailboxes.MailAccessModeState(context.Background(), m.ID, tenantID); err == nil && eff != "" {
			effective = eff
		}
	}
	configured := m.MailAccessMode
	if configured == "" {
		configured = string(adminmailbox.MailAccessInherit)
	}
	return PlatformMailbox{
		ID: m.ID, TenantID: tenantID, DomainID: m.DomainID, Email: m.Email, Name: m.Name,
		Status: string(m.Status), IsAdmin: m.IsAdmin, QuotaMB: m.QuotaMB, UsedBytes: m.UsedBytes,
		MailAccessMode: configured, EffectiveMailAccessMode: effective,
		CreatedAt: m.CreatedAt, UpdatedAt: m.UpdatedAt,
	}
}

func (s *Service) GetMailbox(ctx context.Context, id, tenantID uint) (*PlatformMailbox, error) {
	if err := s.requireTenant(tenantID); err != nil {
		return nil, err
	}
	m, err := s.mailboxes.GetMailbox(ctx, id, tenantID)
	if err != nil {
		if errors.Is(err, adminmailbox.ErrMailboxNotFound) {
			return nil, kernel.NotFound("mailbox")
		}
		return nil, kernel.Wrap(kernel.ErrCodeInternal, "get platform mailbox", err)
	}
	if m == nil {
		return nil, kernel.NotFound("mailbox")
	}
	return &PlatformMailbox{
		ID: m.ID, TenantID: tenantID, DomainID: m.DomainID, Email: m.Email, Name: m.Name,
		Status: string(m.Status), IsAdmin: m.IsAdmin, QuotaMB: m.QuotaMB, UsedBytes: m.UsedBytes,
		MailAccessMode:          m.MailAccessMode,
		EffectiveMailAccessMode: m.EffectiveMailAccessMode,
		CreatedAt:               m.CreatedAt, UpdatedAt: m.UpdatedAt,
	}, nil
}

// verifyMailboxOwnership fails closed with NOT_FOUND when the mailbox
// does not belong to the explicit tenant.
func (s *Service) verifyMailboxOwnership(ctx context.Context, id, tenantID uint) error {
	if _, err := s.mailboxes.GetMailbox(ctx, id, tenantID); err != nil {
		if errors.Is(err, adminmailbox.ErrMailboxNotFound) {
			return kernel.NotFound("mailbox")
		}
		return kernel.Wrap(kernel.ErrCodeInternal, "verify platform mailbox ownership", err)
	}
	return nil
}

// UpdateMailboxStatus transitions a mailbox lifecycle state through the
// production admin service (tenant-scoped SQL).
func (s *Service) UpdateMailboxStatus(ctx context.Context, id, tenantID uint, status, reason string, actorID uint) error {
	if err := s.requireTenant(tenantID); err != nil {
		return err
	}
	if err := s.verifyMailboxOwnership(ctx, id, tenantID); err != nil {
		return err
	}
	if err := s.mailboxes.SetStatus(ctx, id, tenantID, adminmailbox.AdminMailboxStatus(status), reason); err != nil {
		return kernel.Wrap(kernel.ErrCodeInternal, "set platform mailbox status", err)
	}
	s.auditRecord(ctx, actorID, "platform.mailbox.status", fmt.Sprintf("mailbox:%d status:%s", id, status), tenantID, "success", reason)
	return nil
}

// UpdateMailboxQuota updates quota through the production admin service
// which enforces domain-bound ceilings.
func (s *Service) UpdateMailboxQuota(ctx context.Context, id, tenantID uint, quotaMB int64, actorID uint) error {
	if err := s.requireTenant(tenantID); err != nil {
		return err
	}
	if quotaMB <= 0 {
		return kernel.ValidationError(map[string]string{"quota_mb": "must be a positive integer"})
	}
	if err := s.verifyMailboxOwnership(ctx, id, tenantID); err != nil {
		return err
	}
	req := adminmailbox.UpdateMailboxRequest{QuotaMB: &quotaMB}
	if _, err := s.mailboxes.UpdateMailbox(ctx, id, tenantID, req); err != nil {
		return kernel.Wrap(kernel.ErrCodeInternal, "set platform mailbox quota", err)
	}
	s.auditRecord(ctx, actorID, "platform.mailbox.quota", fmt.Sprintf("mailbox:%d quota_mb:%d", id, quotaMB), tenantID, "success", "")
	return nil
}

// ResetMailboxPassword uses the production secure reset service. It
// returns the generated password exactly once (the service contract
// supports generation); the caller must never log or cache it.
func (s *Service) ResetMailboxPassword(ctx context.Context, id, tenantID uint, actorID uint) (string, error) {
	if err := s.requireTenant(tenantID); err != nil {
		return "", err
	}
	if err := s.verifyMailboxOwnership(ctx, id, tenantID); err != nil {
		return "", err
	}
	pw, err := s.mailboxes.ResetPassword(ctx, id, tenantID)
	if err != nil {
		return "", kernel.Wrap(kernel.ErrCodeInternal, "reset platform mailbox password", err)
	}
	s.auditRecord(ctx, actorID, "platform.mailbox.password_reset", fmt.Sprintf("mailbox:%d", id), tenantID, "success", "")
	return pw, nil
}

// SoftDeleteMailbox marks a mailbox deleted through the production
// service. Confirmation is validated by the handler for destructive
// actions.
func (s *Service) SoftDeleteMailbox(ctx context.Context, id, tenantID uint, actorID uint) error {
	if err := s.requireTenant(tenantID); err != nil {
		return err
	}
	if err := s.verifyMailboxOwnership(ctx, id, tenantID); err != nil {
		return err
	}
	if err := s.mailboxes.SoftDeleteMailbox(ctx, id, tenantID, "platform super admin"); err != nil {
		return kernel.Wrap(kernel.ErrCodeInternal, "soft delete platform mailbox", err)
	}
	s.auditRecord(ctx, actorID, "platform.mailbox.delete", fmt.Sprintf("mailbox:%d", id), tenantID, "success", "")
	return nil
}

// ── Aliases ────────────────────────────────────────────────────────

func (s *Service) ListAliases(ctx context.Context, f PlatformAliasFilter) (*PlatformAliasList, error) {
	if err := s.requireTenant(f.TenantID); err != nil {
		return nil, err
	}
	aliases, total, err := s.repo.ListAliases(ctx, f)
	if err != nil {
		return nil, kernel.Wrap(kernel.ErrCodeInternal, "list platform aliases", err)
	}
	return &PlatformAliasList{Aliases: aliases, Total: total, Limit: sanitizeLimit(f.Limit), Offset: f.Offset}, nil
}

func (s *Service) GetAlias(ctx context.Context, id, tenantID uint) (*PlatformAlias, error) {
	if err := s.requireTenant(tenantID); err != nil {
		return nil, err
	}
	a, err := s.repo.GetAlias(ctx, id, tenantID)
	if err != nil {
		return nil, kernel.Wrap(kernel.ErrCodeInternal, "get platform alias", err)
	}
	if a == nil {
		return nil, kernel.NotFound("alias")
	}
	return a, nil
}

// CreateAlias verifies the domain is tenant-owned, rejects a
// from-address that already exists (conflict), rejects a loop where
// from == to, and persists via the platform repository.
func (s *Service) CreateAlias(ctx context.Context, tenantID, domainID uint, fromAddr, toAddr string, actorID uint) (*PlatformAlias, error) {
	if err := s.requireTenant(tenantID); err != nil {
		return nil, err
	}
	fromAddr = strings.ToLower(strings.TrimSpace(fromAddr))
	toAddr = strings.ToLower(strings.TrimSpace(toAddr))
	if fromAddr == "" || toAddr == "" || !strings.Contains(fromAddr, "@") || !strings.Contains(toAddr, "@") {
		return nil, kernel.ValidationError(map[string]string{"from_addr": "valid email addresses required"})
	}
	if fromAddr == toAddr {
		return nil, kernel.NewError(kernel.ErrCodeValidation, "alias loop: from and to must differ")
	}
	// Domain ownership check through the production service.
	if _, err := s.domains.GetDomain(ctx, domainID, tenantID); err != nil || err == nil {
		d, derr := s.domains.GetDomain(ctx, domainID, tenantID)
		if derr != nil || d == nil {
			return nil, kernel.NotFound("domain")
		}
	}
	if err := s.requireTenant(tenantID); err != nil {
		return nil, err
	}
	a, err := s.repo.CreateAlias(ctx, tenantID, domainID, fromAddr, toAddr)
	if err != nil {
		if strings.Contains(err.Error(), "UNIQUE") || strings.Contains(err.Error(), "duplicate") {
			return nil, kernel.NewError(kernel.ErrCodeConflict, "alias already exists")
		}
		return nil, kernel.Wrap(kernel.ErrCodeInternal, "create platform alias", err)
	}
	s.auditRecord(ctx, actorID, "platform.alias.create", fmt.Sprintf("alias:%d", a.ID), tenantID, "success", "")
	return a, nil
}

func (s *Service) DeleteAlias(ctx context.Context, id, tenantID uint, actorID uint) error {
	if err := s.requireTenant(tenantID); err != nil {
		return err
	}
	ok, err := s.repo.DeleteAlias(ctx, id, tenantID)
	if err != nil {
		return kernel.Wrap(kernel.ErrCodeInternal, "delete platform alias", err)
	}
	if !ok {
		return kernel.NotFound("alias")
	}
	s.auditRecord(ctx, actorID, "platform.alias.delete", fmt.Sprintf("alias:%d", id), tenantID, "success", "")
	return nil
}

// ── Groups ─────────────────────────────────────────────────────────

func (s *Service) ListGroups(ctx context.Context, f PlatformGroupFilter) (*PlatformGroupList, error) {
	if err := s.requireTenant(f.TenantID); err != nil {
		return nil, err
	}
	groups, total, err := s.repo.ListGroups(ctx, f)
	if err != nil {
		return nil, kernel.Wrap(kernel.ErrCodeInternal, "list platform groups", err)
	}
	return &PlatformGroupList{Groups: groups, Total: total, Limit: sanitizeLimit(f.Limit), Offset: f.Offset}, nil
}

func (s *Service) GetGroup(ctx context.Context, id, tenantID uint) (*PlatformGroup, error) {
	if err := s.requireTenant(tenantID); err != nil {
		return nil, err
	}
	g, err := s.repo.GetGroup(ctx, id, tenantID)
	if err != nil {
		return nil, kernel.Wrap(kernel.ErrCodeInternal, "get platform group", err)
	}
	if g == nil {
		return nil, kernel.NotFound("group")
	}
	return g, nil
}

func (s *Service) ListGroupMembers(ctx context.Context, id, tenantID uint) ([]string, error) {
	if err := s.requireTenant(tenantID); err != nil {
		return nil, err
	}
	if _, err := s.repo.GetGroup(ctx, id, tenantID); err != nil || err == nil {
		g, gerr := s.repo.GetGroup(ctx, id, tenantID)
		if gerr != nil || g == nil {
			return nil, kernel.NotFound("group")
		}
	}
	return s.repo.ListGroupMembers(ctx, id, tenantID)
}

// ── Bulk mailbox operations ────────────────────────────────────────

// BulkMailboxStatus applies a status transition to up to 500 mailboxes
// within one explicit tenant/domain. It reports per-row style totals
// via RowsAffected and rejects invalid actions.
func (s *Service) BulkMailboxStatus(ctx context.Context, req BulkMailboxRequest, actorID uint) (*BulkMailboxResult, error) {
	if err := s.requireTenant(req.TenantID); err != nil {
		return nil, err
	}
	if len(req.IDs) == 0 || len(req.IDs) > 500 {
		return nil, kernel.ValidationError(map[string]string{"ids": "between 1 and 500 ids required"})
	}
	var status string
	switch req.Action {
	case BulkMailboxSuspend:
		status = "suspended"
	case BulkMailboxReactivate:
		status = "active"
	case BulkMailboxDelete:
		status = "deleted"
	default:
		return nil, kernel.ValidationError(map[string]string{"action": "must be suspend, reactivate, or delete"})
	}
	if status == "deleted" {
		// Soft-delete via the production lifecycle service per row so
		// the soft-delete semantics and audit stay consistent.
		succeeded := 0
		var failed []BulkMailboxFailure
		for _, id := range req.IDs {
			if err := s.mailboxes.SoftDeleteMailbox(ctx, id, req.TenantID, "platform bulk delete"); err != nil {
				failed = append(failed, BulkMailboxFailure{ID: id, Error: "delete failed"})
				continue
			}
			succeeded++
		}
		s.auditRecord(ctx, actorID, "platform.mailbox.bulk_delete", fmt.Sprintf("tenant:%d succeeded:%d total:%d", req.TenantID, succeeded, len(req.IDs)), req.TenantID, "success", req.Reason)
		return &BulkMailboxResult{Total: len(req.IDs), Succeeded: succeeded, Failed: failed}, nil
	}
	n, err := s.repo.BulkSetMailboxStatus(ctx, req.TenantID, req.DomainID, req.IDs, status, s.now())
	if err != nil {
		return nil, kernel.Wrap(kernel.ErrCodeInternal, "bulk mailbox status", err)
	}
	s.auditRecord(ctx, actorID, "platform.mailbox.bulk_status", fmt.Sprintf("tenant:%d action:%s affected:%d", req.TenantID, req.Action, n), req.TenantID, "success", req.Reason)
	return &BulkMailboxResult{Total: len(req.IDs), Succeeded: int(n)}, nil
}

// ── helpers ────────────────────────────────────────────────────────

func stringPtrIf(cond bool, v string) *string {
	if !cond {
		return nil
	}
	return &v
}

func uintPtrIf(cond bool, v uint) *uint {
	if !cond {
		return nil
	}
	return &v
}

var _ = errors.Is
