package handlers

// Public MTA-STS hosting (DNS-AUTOMATION-2G).
//
// RFC 8461 §4.2 requires the operator to host the MTA-STS
// policy file at:
//
//   https://mta-sts.<domain>/.well-known/mta-sts.txt
//
// Until 2G this lived only inside the dnsops plan payload —
// the operator had to host the file themselves. 2G serves
// the file directly from the Orvix backend at
//
//   GET /.well-known/mta-sts.txt
//
// for any host that resolves to a provisioned Orvix domain
// (coremail_domains row, deleted_at IS NULL). The endpoint
// is public (no auth, no CSRF) and returns plain text —
// exactly what an MTA-STS probe expects. It does NOT
// return any admin data, JSON, or secrets.
//
// The matching A / AAAA records for mta-sts.<domain> are
// generated by the dnsops Plan generator and surfaced to the
// admin UI; the actual policy content comes from the dnsops
// Plan so the same generator / handler pair stays the
// single source of truth for both the DNS records and the
// hosted policy body.

import (
	"context"
	"fmt"
	"strings"

	"github.com/gofiber/fiber/v3"
	"github.com/orvix/orvix/internal/dnsops"
)

// mtaStsPolicyBody returns the policy text the handler
// returns for a domain. The body is plain text per RFC
// 8461; it contains no admin data, no token, no private
// key, no stack trace. Each line ends with \n. The total
// size is bounded (~200 bytes) so the response is well
// under any rate limiter's 4 KB buffer.
//
// The mail host is read from cfg.CoreMail.Hostname with a
// fallback to "mail.<domain>". The MTA-STS policy body
// never depends on the public IP (the policy is mode + mx
// + max_age), so the handler does not require a configured
// dns.public_ipv4 to host the file. This decouples the
// public endpoint from the private plan generation path.
func (h *Handler) mtaStsPolicyBody(domain string) string {
	mailHost := strings.TrimSpace(h.cfg.CoreMail.Hostname)
	if mailHost == "" {
		mailHost = "mail." + domain
	}
	mode := "testing"
	maxAge := "86400"
	return fmt.Sprintf("version: STSv1\nmode: %s\nmx: %s\nmax_age: %s\n",
		mode, mailHost, maxAge)
}

// domainHasMTASTSConfig reports whether the supplied domain
// has any active coremail_domains row. The lookup is
// case-insensitive and ignores soft-deleted rows.
func (h *Handler) domainHasMTASTSConfig(ctx context.Context, domain string) (bool, error) {
	domain = strings.ToLower(strings.TrimSpace(domain))
	if domain == "" {
		return false, nil
	}
	sqlDB, err := h.db.DB()
	if err != nil {
		return false, err
	}
	var count int64
	row := sqlDB.QueryRowContext(ctx,
		h.sqlQ(`SELECT COUNT(*) FROM coremail_domains WHERE LOWER(name) = ? AND deleted_at IS NULL`),
		domain)
	if err := row.Scan(&count); err != nil {
		return false, err
	}
	return count > 0, nil
}

// GetPublicMTASTS serves the MTA-STS policy file at the
// canonical path /.well-known/mta-sts.txt. The handler is
// public (no admin auth) and returns:
//
//   - 200 text/plain with the policy body when the
//     request's Host header maps to a provisioned Orvix
//     domain (mta-sts.<domain>).
//   - 404 when the host does not map to a provisioned
//     domain, or when the path is anything other than
//     exactly /.well-known/mta-sts.txt.
//
// The handler does NOT consult the dnsops.Generator for
// the policy body because the generator requires a
// configured public IPv4 (Plan.Validate fails otherwise);
// the MTA-STS hosted file does not need the public IP —
// the policy is purely mode + mx + max_age. The handler
// therefore constructs the policy body directly from the
// configured mail host, keeping the public endpoint
// decoupled from the private plan generation path.
func (h *Handler) GetPublicMTASTS(c fiber.Ctx) error {
	// Exact path check: this handler serves ONLY
	// /.well-known/mta-sts.txt. Any other path under
	// /.well-known/* is 404.
	if c.Path() != "/.well-known/mta-sts.txt" {
		return c.SendStatus(fiber.StatusNotFound)
	}
	// Extract the domain from the Host header. The
	// canonical form is "mta-sts.<domain>"; we accept any
	// host so the same handler can serve multi-tenant
	// deployments behind a Caddy vhost matcher.
	host := strings.ToLower(strings.TrimSpace(c.Hostname()))
	if host == "" {
		return c.SendStatus(fiber.StatusNotFound)
	}
	// Strip a port if present (Host() includes ":port"
	// when not the default port). Namecheap / Caddy
	// typically terminates TLS on 443.
	if i := strings.IndexByte(host, ':'); i >= 0 {
		host = host[:i]
	}
	domain := mtaStsDomainFromHost(host)
	if domain == "" {
		return c.SendStatus(fiber.StatusNotFound)
	}
	// Verify the domain is provisioned. The check is
	// case-insensitive and ignores soft-deleted rows.
	ok, err := h.domainHasMTASTSConfig(c.Context(), domain)
	if err != nil {
		// We do NOT echo the DB error to the public
		// endpoint. A 503 with a generic note is the
		// only safe response.
		c.Set("Content-Type", "text/plain; charset=utf-8")
		return c.Status(fiber.StatusServiceUnavailable).SendString(
			"mta-sts policy temporarily unavailable")
	}
	if !ok {
		return c.SendStatus(fiber.StatusNotFound)
	}
	c.Set("Content-Type", "text/plain; charset=utf-8")
	c.Set("Cache-Control", "public, max-age=300")
	return c.SendString(h.mtaStsPolicyBody(domain))
}

// mtaStsDomainFromHost returns the domain portion of an
// mta-sts.<domain> hostname, or "" when the input is not
// an mta-sts.* host. We accept the bare apex (a probe
// hitting mta-sts.<domain> with no port) and the IP-only
// form. Apexes that happen to be "mta-sts" themselves
// (no subdomain) yield "".
func mtaStsDomainFromHost(host string) string {
	host = strings.ToLower(strings.TrimSpace(host))
	if host == "" {
		return ""
	}
	const prefix = "mta-sts."
	if !strings.HasPrefix(host, prefix) {
		return ""
	}
	rest := strings.TrimPrefix(host, prefix)
	if rest == "" {
		return ""
	}
	// The dnsops.Generator.validateDomain rules apply
	// transitively: at least one dot, no whitespace, no
	// protocol. We do a quick shape check here so the
	// public endpoint does not consult the DB for
	// obviously invalid hosts.
	if strings.ContainsAny(rest, " \t\n\r/") {
		return ""
	}
	if !strings.Contains(rest, ".") {
		return ""
	}
	return rest
}

// silence "imported and not used" warning if the file's
// imports shrink during future refactors.
var _ = dnsops.Record{}
